name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI Quality & Security"] # Vérifie bien que c'est le 'name' exact de ton ci.yml
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Condition cruciale : on ne lance que si la CI a réussi (success)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: ./app_api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:${{ github.sha }}

      - name: Build and Push Front
        uses: docker/build-push-action@v5
        with:
          context: ./app_front
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-front:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-front:${{ github.sha }}